name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      submodules: true
      lfs: true
    - name: Build inside a docker container
      uses: docker://ashwinvis/latex-pandoc-python
      run: |
        tlmgr update --self
